export const NODE_TYPES = {
  UNSET: 0, // For safety; should not be used.
  DATA: 1,
  FUNCTION: 2,
  USER_INPUT: 3,
}

export const ERROR_TYPES = {
  UNSET: 0, // For safety; should not be used.
  GRAPH_ERROR: 1,
  PARSER_ERROR: 2,
  WORKER_ERROR: 3,
  SAMPLING_ERROR: 4,
}
export const ERROR_SUBTYPES = {
  GRAPH_ERROR_SUBTYPES: {
    UNSET: 0, // For safety; should not be used.
    MISSING_INPUT_ERROR: 1,
    IN_INFINITE_LOOP: 2,
    INVALID_ANCESTOR_ERROR: 3,
    DUPLICATE_ID_ERROR: 4,
  },
  PARSER_ERROR_SUBTYPES: {
    NULL_WITH_TEXT_ERROR: 5,
    MISSING_FUNCTION_BODY: 6,
    INVALID_RANGE_ORDERING: 7,
    FUNCTIONS_CONTAIN_UNITS_ERROR: 8,
    INCOMPLETE_FUNCTION_ERROR: 9,
  },
  WORKER_ERROR_SUBTYPES: {
    NO_DATA_PASSED_ERROR: 10,
    NO_EXPR_PASSED_ERROR: 11,
    NO_NUMSAMPLES_PASSED_ERROR: 12,
    ZERO_SAMPLES_REQUESTED_ERROR: 13,
  },
  SAMPLING_ERROR_SUBTYPES: {
    UNEXPECTED_END_OF_EXPRESSION_ERROR: 14,
    DIVIDE_BY_ZERO_ERROR: 15,
  },
}
